== Advanced techniques

// ----------------------------------------------------------------------
[[recipe_template_values]]
=== How to add tracking and authorization details (TBD)

==== Problem

How can clients discover operational details about 

==== Solution


==== Discussion


==== Example


// ----------------------------------------------------------------------
=== How to reduce the size of Mason documents (TBD)

==== Problem

Hypermedia controls, long control names, meta information and embedded schemas takes up bandwith - how can we reduce the size of a Mason document?

==== Solution

Use a combination of CURIEs, the "prefer" header and linked schemas instead of embedded.

==== Discussion


==== Example


// ----------------------------------------------------------------------
=== How to create user interfaces from a Mason document (TBD)

==== Problem

Mason does not include any user interface information - how can clients then create dynamic user interfaces?

==== Solution

1) Use the JSON schema information to generate UI (using for instance tools like XX and YY).

2) Include layout information as normal API data (using a custom way of describing the layout).

3) Include a reference to some sort of external user interface template (a'la XML stylesheets) (using a custom way of describing the layout).

==== Discussion


==== Example


